version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "5173:5173" # dev mode vite server
    command: npm run dev

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # NGINX serving production build

