apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'GIT_REPOSITORY_URL'    # <-- REPLACE with your repository HTTPS URL
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: canary-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

