apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-app
  namespace: canary-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
        - name: web
          image: milanr853/canary-deployment:99b9b4994072724267cbef139d03d57809e4aa5d
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: { duration: 60 }
        - setWeight: 30
        - pause: { duration: 60 }
        - setWeight: 60
        - pause: { duration: 60 }
      analysis:
        templates:
          - name: canary-analysis
            templateName: canary-analysis

