apiVersion: v1
kind: Service
metadata:
  name: canary-app
  namespace: canary-deployment
spec:
  type: NodePort
  selector:
    app: canary-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
