apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/milanr853/canary-deployment.git'   # <-- Replace with actual repo URL
    targetRevision: main                                           # <-- Use "main" or "master"
    path: infra/k8s   
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: canary-deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

